Repository tokilabs/atqr, pull requests merged in 2023-01, with the labels that each got.

#73 Alberto/atqr 128 create notifications templatedatatypes
  libs/atqr/domain/package.json
  libs/atqr/domain/src/lib/EmailService/dtos/index.ts
  libs/atqr/domain/src/lib/EmailService/dtos/messageContent.dto.ts
  libs/atqr/domain/src/lib/domain-spec/concept-set/Notifications.disl
  libs/atqr/domain/src/lib/notifications/index.ts
  libs/atqr/domain/src/lib/notifications/interfaces/index.ts
  libs/atqr/domain/src/lib/notifications/interfaces/templateDataType.interface.ts
  libs/atqr/domain/src/lib/notifications/templateDataType.ts
Labels: enhancement

#81 Docs: Describe User Repository in Disl (Jira: ATQR-83 )
  libs/atqr/domain/src/lib/domain-spec/services/User.disl
Labels: documentation, ready-for-work

#93 Create notifications value objects
  .vscode/settings.json
  libs/atqr/domain/src/lib/domain-spec/concept-set/Notifications.disl
  libs/atqr/domain/src/lib/types/notification.types.ts
  libs/atqr/domain/src/lib/valueObjects/ForbiddenEmailAddress.ts
  libs/atqr/domain/src/lib/valueObjects/notification.ts
  libs/atqr/domain/src/lib/valueObjects/notificationLogEntry.valueObject.ts
  libs/atqr/domain/src/utils/valueObject.ts
  package.json
  yarn.lock
Labels: ready-for-work

#82 Implement User entity (Jira: ATQR-84 )
  .github/ISSUE_TEMPLATE/feature_request.md
  libs/atqr/domain/src/lib/challenge/challenge.entity.ts
  libs/atqr/domain/src/lib/user/user.entity.ts
  libs/atqr/domain/src/lib/valueObjects/enrollment.ts
  libs/atqr/domain/src/lib/valueObjects/index.ts
  libs/atqr/domain/src/lib/valueObjects/invitee.ts
  libs/atqr/domain/src/lib/valueObjects/officiation.ts
Labels: blocked

#83 Create email service interface on domain (Jira: ATQR-81 )
  libs/atqr/domain/src/index.ts
  libs/atqr/domain/src/lib/EmailService/index.ts
  libs/atqr/domain/src/lib/EmailService/interfaces/email.interface.ts
  libs/atqr/domain/src/lib/EmailService/interfaces/index.ts
  libs/atqr/domain/src/lib/services/notification/interfaces/index.ts
  libs/atqr/domain/src/lib/services/notification/interfaces/mailer.interface.ts
  libs/atqr/domain/src/lib/services/notification/mailer.interface.ts
  libs/atqr/domain/src/lib/valueObjects/contact.ts
  libs/atqr/domain/src/lib/valueObjects/email.ts
  libs/atqr/domain/src/lib/valueObjects/emailAddress.ts
  libs/atqr/domain/src/lib/valueObjects/index.ts
  libs/atqr/domain/src/lib/valueObjects/invitee.ts
  libs/atqr/domain/src/utils/index.ts
Labels: reviewer training
